
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://projetocrianca.c46lzpht7sam.us-east-1.rds.amazonaws.com:5432/projetoprofissionais?createDatabaseIfNotExist=true
    username: projetocrianca
    password: "#Projetocrianca12345678"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update